#!/usr/bin/env python3
"""Generate css/icons.css: every assets/icons/*.svg as an inline data-URI mask.

Inline masks make the icon set part of the stylesheet, so a page render no longer starts one
request per icon (12 to 25 per page). Run after adding or changing an icon:

    python3 prototype-oblique/scripts/build-icons.py
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
ICONS = ROOT / 'assets' / 'icons'
OUTPUT = ROOT / 'css' / 'icons.css'

# Characters that are not safe in an unquoted data URI inside url("...").
ESCAPES = {'"': "'", '<': '%3C', '>': '%3E', '#': '%23', '%': '%25', '{': '%7B', '}': '%7D'}


def data_uri(svg: str) -> str:
    compact = re.sub(r'\s+', ' ', svg.strip())
    compact = re.sub(r'> <', '><', compact)
    encoded = ''.join(ESCAPES.get(ch, ch) for ch in compact)
    return f'url("data:image/svg+xml,{encoded}")'


def main() -> None:
    files = sorted(ICONS.glob('*.svg'))
    if not files:
        raise SystemExit(f'No icons found in {ICONS}')
    lines = [
        '/* Generated by scripts/build-icons.py from assets/icons/*.svg – do not edit by hand.',
        '   Each icon is an inline SVG mask: the stylesheet carries the whole set in one request,',
        '   and .ob-icon (main.css) paints the mask in currentColor. */',
        ':root {',
    ]
    names = []
    for file in files:
        name = file.stem
        if not re.fullmatch(r'[a-z0-9_]+', name):
            raise SystemExit(f'Icon name must be [a-z0-9_]: {file.name}')
        names.append(name)
        lines.append(f'  --ob-icon-{name}: {data_uri(file.read_text(encoding="utf-8"))};')
    lines.append('}')
    lines.extend(f'.ob-icon-{name} {{ --icon: var(--ob-icon-{name}); }}' for name in names)
    OUTPUT.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{OUTPUT.relative_to(ROOT)}: {len(names)} icons, {OUTPUT.stat().st_size} bytes')


if __name__ == '__main__':
    main()
