/* Catalog scope, applied filter chips, multi-select facets and selection are independent. */
const assert = require('node:assert/strict');
const path = require('node:path');
const { workspace } = require('./print-test-helpers.cjs');
(async () => {
  const test = await workspace(), { page, choose, visit, open, download, settle, output, scrollToPage } = test;
  const scope = label => page.locator('#diagram-tree .ob-tree-link').filter({ has: page.locator('.ob-tree-label', { hasText: new RegExp('^' + label + '$') }) }).click();
  const filter = async (facet, title) => {
    await page.locator('[data-diagram-action="filters"]').click();
    assert.equal(await page.locator('[data-diagram-action="all-facets"], #diagram-settings-form [type="submit"]').count(), 0);
    assert.equal(await page.locator('[data-diagram-facet][hidden]').count(), 0);
    await page.locator(`[data-diagram-facet="${facet}"] .ob-check`).filter({ hasText: title }).locator('input').check();
    await page.locator('[data-diagram-action="dismiss"]').click(); await settle(page);
  };
  try {
    await visit('#/tables'); await open();
    await choose('[data-diagram-setting="layout"]', 'list');
    const url = page.url();
    await scope('GWR'); assert.equal(page.url(), url);
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 7);
    await filter('status', 'Entwurf');
    assert(await page.locator('.ob-export-filterbar [data-diagram-action="reset-filters"]').isVisible());
    assert.equal(await page.locator('[data-diagram-page]').count(), 0, 'No blank export pages');
    assert(await page.locator('[data-diagram-action="download"]').isDisabled());
    assert(await page.locator('.ob-export-empty').isVisible());
    await page.screenshot({ path: path.join(output, 'print-empty.png') });
    await page.locator('[data-diagram-remove]').click();
    assert(await page.locator('.ob-export-filterbar [data-diagram-action="reset-filters"]').isHidden());
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 7);
    const checkbox = page.locator('[data-diagram-entity]').first(), id = await checkbox.getAttribute('data-diagram-entity');
    await checkbox.uncheck();
    await scope('Datentabellen');
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 29, 'Scope expansion preserves exclusions');
    await scope('GWR');
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 6);
    await page.locator(`[data-diagram-entity="${id}"]`).check();
    await page.locator('[data-diagram-action="filters"]').click();
    await page.locator('[data-diagram-facet="domain"] .ob-check').filter({ hasText: 'Architektonische Sicht' }).locator('input').check();
    await page.locator('[data-diagram-facet="domain"] .ob-check').filter({ hasText: 'Mieter Management' }).locator('input').check();
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 4, 'OR within a facet');
    assert.equal(await page.locator('[data-diagram-remove]').count(), 2);
    assert.equal(await page.locator('#diagram-popover:popover-open').count(), 1, 'Filtering keeps the dropdown open');
    await page.locator('[data-diagram-action="dismiss"]').click();
    await download('filtered-tables');
    await scope('Geschäftsobjekte');
    assert((await page.evaluate(() => window.printTest.layout.entityCount)) > 0, 'Domain filters remain meaningful across entity types');
    await scope('Datentabellen'); await scope('GWR');
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 4);
    await page.locator('[data-diagram-action="filters"]').click();
    const choice = page.locator('[data-diagram-facet="domain"] input:checked').first();
    await choice.focus();
    await choice.evaluate(input => { window.filterChoice = input; window.filterScroll = input.closest('.ob-export-popover-body').scrollTop; });
    await page.keyboard.press('Space');
    const filteredCount = await page.evaluate(() => window.printTest.layout.entityCount);
    assert(filteredCount > 0 && filteredCount < 4, 'Unchecking immediately filters the preview');
    assert(await page.evaluate(() => document.activeElement === window.filterChoice && window.filterChoice.isConnected && window.filterChoice.closest('.ob-export-popover-body').scrollTop === window.filterScroll));
    await page.keyboard.press('Escape');
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), filteredCount, 'Escape retains immediate filter changes');
    await page.locator('.ob-export-filterbar [data-diagram-action="reset-filters"]').click();
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 7, 'Reset keeps the tree scope');
    await scope('Gebäude (GWR_GEBAEUDE)'.replace(/[()]/g, '\\$&'));
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 1);
    assert.equal(await page.evaluate(() => window.printTest.layout.fieldCount), 39);
    assert.equal(await page.evaluate(() => window.printTest.layout.columns), 1, 'Entity profiles use the full page width');
    await page.locator('#diagram-find').fill('not a match');
    assert.equal(await page.evaluate(() => window.printTest.layout.fieldCount), 39, 'Tree finder does not filter exported rows');
    await page.locator('#diagram-find').fill('');
    await scope('Referenzdaten');
    assert.equal(await page.evaluate(() => window.printTest.snapshot.kind), 'refs');
    assert((await page.evaluate(() => window.printTest.layout.fieldCount)) > 500);
    await page.evaluate(() => { window.printTest.settings.selected = window.printTest.snapshot.entities.filter(entity => entity.rows.length > 0 && entity.rows.length < 10).slice(0, 2).map(entity => entity.id); });
    await choose('[data-diagram-setting="layout"]', 'list');
    await download('reference-codes');
    await scope('Datenprodukte');
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 5);
    await scope('API-Verzeichnis');
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 7);
    assert((await page.evaluate(() => window.printTest.layout.fieldCount)) > 0);
    await download('api-endpoints');
    await page.locator('.ob-export-header [data-diagram-action="close"]').first().click();
    await visit('#/tables?filter=GWR'); await open();
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), await page.evaluate(() => DK.data.tables.filter(e => DK.data.matchesCollection('tables', e, 'GWR')).length));
    assert(await page.locator('[data-diagram-action="clear-query"]').isVisible());
    await page.locator('[data-diagram-action="clear-query"]').click();
    assert.equal(await page.evaluate(() => window.printTest.layout.entityCount), 30);
    const checks = await page.evaluate(() => {
      const { snapshot, settings } = window.printTest;
      const frozen = JSON.stringify(snapshot.entities);
      const original = DK.data.tables[0].fields.length;
      DK.data.tables[0].fields.push({ technicalName: 'MUTATED_AFTER_OPEN', labels: { de: 'Mutation' } });
      const unchanged = JSON.stringify(snapshot.entities) === frozen;
      DK.data.tables[0].fields.splice(original);
      const unknown = DK.diagram.exportEntities(snapshot, { ...settings, filters: { status: ['unknown-id'] } });
      const keys = Object.entries(DK.data.i18n).filter(([key]) => key.startsWith('print.'));
      return { unchanged, unknown: unknown.length, brokenTranslations: keys.filter(([, labels]) => ['de', 'fr', 'it', 'en'].some(lang => !labels[lang] || labels[lang].includes('?'))).map(([key]) => key) };
    });
    assert.equal(checks.unchanged, true); assert.equal(checks.unknown, 0); assert.deepEqual(checks.brokenTranslations, []);
    await choose('#diagram-zoom-mode', 'width');
    await scrollToPage(1);
    await page.screenshot({ path: path.join(output, 'print-grid-desktop.png') });
    assert.deepEqual(test.errors, []);
    console.log('PASS: tree scope, immediate multi-value filters, retained focus, empty states, selection memory, all sections and frozen data');
  } finally { await test.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
